/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : bigint,
  'description' : string,
  'subjectId' : bigint,
}
export interface DailyStats { 'totalSeconds' : bigint, 'dayIndex' : bigint }
export interface StudySession {
  'id' : bigint,
  'date' : bigint,
  'createdAt' : bigint,
  'durationSeconds' : bigint,
  'subjectId' : bigint,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'colorHex' : string,
}
export interface SubjectStats { 'totalSeconds' : bigint, 'subjectId' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAssignment' : ActorMethod<[bigint, string, string, bigint], Assignment>,
  'addSubject' : ActorMethod<[string, string], Subject>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAssignment' : ActorMethod<[bigint], boolean>,
  'deleteSubject' : ActorMethod<[bigint], boolean>,
  'getAssignments' : ActorMethod<[], Array<Assignment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSessionsByDateRange' : ActorMethod<[bigint, bigint], Array<StudySession>>,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getSubjectStats' : ActorMethod<[], Array<SubjectStats>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyStats' : ActorMethod<[bigint], Array<DailyStats>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logStudySession' : ActorMethod<[bigint, bigint, bigint], StudySession>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleAssignment' : ActorMethod<[bigint], [] | [Assignment]>,
  'updateAssignment' : ActorMethod<
    [bigint, string, string, bigint],
    [] | [Assignment]
  >,
  'updateSubject' : ActorMethod<[bigint, string, string], [] | [Subject]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];